fullnameOverride: "jenkins"

master:
  imageTag: "lts-alpine"
  imagePullPolicy: Always

  adminPassword: [ADMIN_PASSWORD]
  hostName: [HOSTNAME]

  serviceType: ClusterIP
  servicePort: 8080

  runAsUser: 1000
  fsGroup: 1000

  useSecurity: true
  # Allows to configure different SecurityRealm using Jenkins XML
  securityRealm: |-
    <securityRealm class="hudson.security.LegacySecurityRealm"/>
  # Allows to configure different AuthorizationStrategy using Jenkins XML
  # For admin authorization selection "Logged-in users can do anything"
  authorizationStrategy: |-
     <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
       <denyAnonymousReadAccess>true</denyAnonymousReadAccess>
     </authorizationStrategy>

  installPlugins:
  - kubernetes:1.18.1
  - workflow-job:2.34
  - workflow-aggregator:2.6
  - credentials-binding:1.20
  - bitbucket:1.1.10

  ingress:
    enabled: true
    hostName: [HOSTNAME]
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: [CLUSTER_ISSUER]
      ingress.kubernetes.io/secure-backends: "true"

    tls:
      - hosts:
        - [HOSTNAME]
        secretName: jenkins-tls-[CLUSTER_ISSUER]

persistence:
  enabled: true
  existingClaim: [PVC_NAME]
  size: 5Gi
